services:
  - type: web
    name: visual-search
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: WOOCOMMERCE_URL
        value: https://cgbshop1.com/wp-json/wc/v3
      - key: WOOCOMMERCE_KEY
        value: ck_da1507a982310e8a29d704df57b4e886b26d528a
      - key: WOOCOMMERCE_SECRET
        value: cs_2917aeffff79c6bb2427849b617f0c992959f301
    python_version: "3.11.10"