<<<<<<< HEAD
name: Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
=======
name: Deploy to Vercel
on:
  push:
    branches:
      - master
>>>>>>> origin/master

jobs:
  deploy:
    runs-on: ubuntu-latest
<<<<<<< HEAD
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Set up environment variables
      env:
        WOOCOMMERCE_URL: ${{ secrets.WOOCOMMERCE_URL }}
        WOOCOMMERCE_KEY: ${{ secrets.WOOCOMMERCE_KEY }}
        WOOCOMMERCE_SECRET: ${{ secrets.WOOCOMMERCE_SECRET }}
      run: |
        echo "WOOCOMMERCE_URL=$WOOCOMMERCE_URL" >> .env
        echo "WOOCOMMERCE_KEY=$WOOCOMMERCE_KEY" >> .env
        echo "WOOCOMMERCE_SECRET=$WOOCOMMERCE_SECRET" >> .env 
=======
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      
      - name: Pull Vercel Environment Information
        env:
          WOOCOMMERCE_URL: ${{ secrets.WOOCOMMERCE_URL }}
          WOOCOMMERCE_KEY: ${{ secrets.WOOCOMMERCE_KEY }}
          WOOCOMMERCE_SECRET: ${{ secrets.WOOCOMMERCE_SECRET }}
        run: vercel pull --yes --environment=production --token=2nMJxl5kdpmdXELH2esdGqFI
      
      - name: Build Project Artifacts
        env:
          WOOCOMMERCE_URL: ${{ secrets.WOOCOMMERCE_URL }}
          WOOCOMMERCE_KEY: ${{ secrets.WOOCOMMERCE_KEY }}
          WOOCOMMERCE_SECRET: ${{ secrets.WOOCOMMERCE_SECRET }}
        run: vercel build --prod --token=2nMJxl5kdpmdXELH2esdGqFI
      
      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: 2nMJxl5kdpmdXELH2esdGqFI
          VERCEL_ORG_ID: 4NeJRWX6MdEjSgWTzwrxy3Md
          VERCEL_PROJECT_ID: prj_YCDZCQRSCoqyDcd5VXodUXcmbzBp
          WOOCOMMERCE_URL: ${{ secrets.WOOCOMMERCE_URL }}
          WOOCOMMERCE_KEY: ${{ secrets.WOOCOMMERCE_KEY }}
          WOOCOMMERCE_SECRET: ${{ secrets.WOOCOMMERCE_SECRET }}
        run: vercel deploy --prebuilt --prod --token=2nMJxl5kdpmdXELH2esdGqFI
>>>>>>> origin/master
