name: Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Set up environment variables
      env:
        WOOCOMMERCE_URL: ${{ secrets.WOOCOMMERCE_URL }}
        WOOCOMMERCE_KEY: ${{ secrets.WOOCOMMERCE_KEY }}
        WOOCOMMERCE_SECRET: ${{ secrets.WOOCOMMERCE_SECRET }}
      run: |
        echo "WOOCOMMERCE_URL=$WOOCOMMERCE_URL" >> .env
        echo "WOOCOMMERCE_KEY=$WOOCOMMERCE_KEY" >> .env
        echo "WOOCOMMERCE_SECRET=$WOOCOMMERCE_SECRET" >> .env 